title: "时间流数据"
description: "记录真实的世界"
url: 
baseurl: ""
author: "Bliky"

port: 4001

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md